### ISSUE TITLE
Running time?

### ISSUE THREAD

**Issue by GuillaumeHolley** [morispi/HG-CoLoR#18]
Hey @morispi,

I am trying to use HG-Color (thank you for the tool) to correct a 5 mbp stretch of ONT reads from the chromosome 1 of HG002. It's about 15K reads with an N50 around 50 kbp. I ran the tool like this:
```
HG-CoLoR --longreads HG002._ONT.fq --shortreads HG002_Illumina.fq --out HG002_ONT_corrected -K 100 --nproc 24 --kmcmem 24
```
The command has been running for 17h now and it hasn't finished. Do you know if something went wrong or is it an expected running time for that data set?

Thank you for the help!
Guillaume

**Comment by morispi** [comment]
Hey Guillaume,

Yeah, HG-CoLoR can be quite long to run. An experiment on a 30x coverage of ONT reads for human chromosome 1 took about 170h to complete. However, I can see you provided fastq reads with --longreads. Be aware that HG-CoLoR only supports fasta at the moment, and that sequences should be in the "one sequence per line" format.

Can you give me more details as to "where" HG-CoLoR currently is? Alignment of SR to the LR? Graph construction? Correction? Content in "HG-CoLoR.stdout" and "HG-CoLoR.stderr" would be enough for me to further help you.

If you used a high coverage of SR data, the graph construction step can, indeed, be pretty long. Can't tell you precise runtimes, as I can't seem to be able to retrieve the detailed logs from the aforementioned experiment. I'll update this issue if I manage to locate them.

Cheers,
Pierre

**Comment by GuillaumeHolley** [comment]
Hey Pierre,

I appreciate your feedback and tips on this run. I completely missed the input FASTA requirement in your README, sorry about that, and I will rerun the tool with an input FASTA long read file rather than FASTQ.  My short read coverage is about 60x so I don't think this is too high. Unfortunately, my job got canceled after 17h (I had required 10h originally) but the last thing written in my `HG-CoLoR.stdout` is:
```
Found 2452750 reads containing duplicate 11-mers in 270 msec!
SA creation start
Written 67807456 bytes
Written 33904128 bytes
SAIS generation time 1990 msec!
SA generation time 7700 msec!
4194305 elements in SA lookup
SA LUT generation time 300 msec!
Written 25427796 bytes
Written 133046181 bytes
Written 101710792 bytes
Written 16777220 bytes
```

For your 30x ONT experiment for chr1, do you remember if the 170h to complete was CPU time or wall-clock time? Just trying to get a rough estimate of how long it would take to run on a full human genome (50x ONT, 60x Illumina).

**Comment by morispi** [comment]
60x coverage of SR doesn't seem too high, but I think it's still gonna take a little while to build the graph with PgSA. Your `HG-CoLoR.stdout` indeed indicates that it stopped during graph construction phase. I'd like to tell you exactly how much time it took for me to build the index on the human chr1 experiment, but it seems like the log files are located on a cluster I no longer have access to... I'll check if this is a password or an account deletion issue and come back to you if I can get any info.

170h was wall-clock time, and HG-CoLoR was run with 16 threads. If it can be on any interest, memory usage was about 50 GB.

For a full human genome, I'm afraid HG-CoLoR would require way too much time. For info, CONSENT (which is a self-correction tool) took 3h to run on chr1. It then took 10 days on the full genome. Since HG-CoLoR took 170h on chr1, I guess we can roughly estimate its runtime at... About one year and a half? :scream: Pretty sure it would actually be quicker, since graph construction is pretty long and only performed once, but I don't believe it would efficiently scale to such an experiment.

**Comment by GuillaumeHolley** [comment]
I see :) I have all the information I need so thank you for the help Pierre, it is much appreciated!
